config/routes.rb
Freekart::Application.routes.draw do

  
 

 
  get "main/coupon"
  

  resources :stores

  resources :products

    resources :vendors
	resources :vendorsessions, only: [:new, :create, :destroy]
 
  resources :contacts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

   
		match '/vendorsignup',  to: 'vendors#new'
		
		match '/vendorsignin',  to: 'vendorsessions#new'
		match '/vendorsignout', to: 'vendorsessions#destroy', via: :delete
		
   

   match '/new', to: 'contacts#new'
   match '/productnew', to: 'products#new' 
   match '/productindex', to: 'products#index' 
    match '/storenew', to: 'stores#new' 
	match '/storeindex', to: 'stores#index' 
	match '/show',  to: 'vendors#show'

	
	
         
  

  match '/signup',  to: 'users#new'

  match '/signin',   to: 'sessions#new'

  match '/signout',  to: 'sessions#destroy', via: :delete
 
	

  match '/home', to: 'shop#home'
   match '/about', to: 'shop#about'
   match '/disclaimer', to: 'shop#disclaimer'
    

   match '/categories', to: 'categories#category'
		match '/bags', to: 'categories#bags'
		match '/travelbags', to: 'categories#travelbags'
		match '/laptopbags', to: 'categories#laptopbags'

		match '/bagsaddpage1', to: 'categories#bagsaddpage1'
		match '/bagsaddpage2', to: 'categories#bagsaddpage2'
		match '/bagsaddpage3', to: 'categories#bagsaddpage3'

		match '/travelbagsaddpage1', to: 'categories#travelbagsaddpage1'
		match '/travelbagsaddpage2', to: 'categories#travelbagsaddpage2'
		match '/travelbagsaddpage3', to: 'categories#travelbagsaddpage3'

		match '/laptopbagsaddpage1', to: 'categories#laptopbagsaddpage1'
		match '/laptopbagsaddpage2', to: 'categories#laptopbagsaddpage2'
		match '/laptopbagsaddpage3', to: 'categories#laptopbagsaddpage3'

		match '/books', to: 'categories#books'
		match '/booksaddpage1', to: 'categories#booksaddpage1'
		match '/booksaddpage2', to: 'categories#booksaddpage2'
		match '/booksaddpage3', to: 'categories#booksaddpage3'

		match '/authors', to: 'categories#authors'	
		match '/authorsaddpage1', to: 'categories#authorsaddpage1'
		match '/authorsaddpage2', to: 'categories#authorsaddpage2'
		match '/authorsaddpage3', to: 'categories#authorsaddpage3'

		match '/english', to: 'categories#english'
		match '/englishaddpage1', to: 'categories#englishaddpage1'
		match '/englishaddpage2', to: 'categories#englishaddpage2'
		match '/englishaddpage3', to: 'categories#englishaddpage3'

		match '/jersey', to: 'categories#jersey'
		match '/jerseyaddpage1', to: 'categories#jerseyaddpage1'
		match '/jerseyaddpage2', to: 'categories#jerseyaddpage2'
		match '/jerseyaddpage3', to: 'categories#jerseyaddpage3'

		match '/menjersey', to: 'categories#menjersey'
		match '/menjerseyaddpage1', to: 'categories#menjerseyaddpage1'
		match '/menjerseyaddpage2', to: 'categories#menjerseyaddpage2'
		match '/menjerseyaddpage3', to: 'categories#menjerseyaddpage3'

		match '/womenjersey', to: 'categories#womenjersey'
		match '/womenjerseyaddpage1', to: 'categories#womenjerseyaddpage1'
		match '/womenjerseyaddpage2', to: 'categories#womenjerseyaddpage2'
		match '/womenjerseyaddpage3', to: 'categories#womenjerseyaddpage3'

		match '/kids', to: 'categories#kids'
		match '/kidsaddpage1', to: 'categories#kidsaddpage1'
		match '/kidsaddpage2', to: 'categories#kidsaddpage2'
		match '/kidsaddpage3', to: 'categories#kidsaddpage3'

match '/list', to: 'categories#list'

	
 

   root :to => 'shop#home'

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :area, 
				 :location,
				 :store_name, 
				:store_url,
				:latitude,
				:longitude


geocoded_by :location
after_validation :geocode, :if => :location_changed? 
				



validates :area,  presence: true
validates :location,  presence: true
validates :store_name,  presence: true
validates :store_url,  presence: true





def self.search(search)
  if search
    find(:all, :conditions => ['store_name LIKE ?', "%#{search}%"])+
	 find(:all, :conditions => ['area LIKE ?', "%#{search}%"])
	
	 
  else
    find(:all)
  end
end





end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
   
	@stores = Store.search(params[:search])
	

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end







  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.label :store_name %><br />
    <%= f.text_field :store_name %>
    
  </div>
  
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  
<div class="field">
    <%= f.label :store_url %>
    <%= f.text_field :store_url %>

  </div>


<div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

<!-- <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>   -->



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
<div style="float:right; margin-right:auto;">

				

		
<table width="700" height="25" border="0"  valign="right">
<tr>
<td valign="left">
	
<%= form_tag stores_path, :method => 'get' do %>
<p>
<%= text_field_tag :search, params[:search], :placeholder => "Store name" %>
<%= submit_tag "Search",  :name => nil  %>
</p>
<% end %>	
</td>

<td valign="center">
<%= form_tag stores_path, :method => 'get' do %>
<p>
<%= text_field_tag :search, params[:search], :placeholder => "Area ", :hidden => 'none' %>
<%= submit_tag "Search",  :name => nil  %>
</p>
<% end %>	
</td>
</tr>


				

			
		
<span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										
										
									
											<center>
												<h2 class="style15"><div class="style1 blok"><strong>Store Details </strong></h2>
												
										    </center>


											
<table width="900" border="2">
  <tr>
    <th width="130">Store name</th>
    
    <th width="130">Area</th>
    <th width="300">Location</th>
	<th width="300">Latitude</th>
	<th width="300">Longitude</th>
   </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.store_name %></td>
	<td><%= store.area %></td>
    <td><%= store.location %></td>

	<td><%= store.latitude %></td>
    <td><%= store.longitude %></td>
	
    <td><%= link_to 'Show', store, class: "btn btn-small btn-default" %></td>
    <td><%= link_to 'Edit', edit_store_path(store) , class: "btn btn-small btn-default"  %></td>
    
  </tr>
<% end %>
</table>












		




											
										
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
								<table width="800" border="0">
									<tr>
							
									</tr> 
									
								</table>
							</td>
						</tr>
					</table>
	 </br>
	 </br>
	 </br>
	 </br>
	 <center>
 <%= link_to 'Add New Store', new_store_path, class: "btn btn-large btn-primary"  %> </center>
	 </br>
	 </br>
	 </br>

	

					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>

app/views/stores/list.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
			<div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										
										<marquee behavior="alternate"> 
										
										</marquee>
									
											<center>
												<h2 class="style15"><div class="style1 blok"><strong></strong></h2>
												
										    </center>




										
											<div class="row">
											
	
												<h4>Storeslist</h4>
														<p>Choose Your Favorite store to get their latest coupons and deals</p>
												
												</div>



												<table width="895" height="420" border="0">
  <tr>
    
	


    <td width = "200" height="100">
	<center>
	 <%= link_to "bigbazaar " , productnew_path  %> 
	 </center></br>
	<center>
	<!-- <marquee direction="up"> -->
   <%= link_to (image_tag "bigbazaar.PNG", :title => "view")%> 
   </marquee>
    </center>
	</td>


    
    

	<td width = "200" height="100">
	<center>
	<%= link_to "Reliance " , categories_path %> 
    </center></br>
	<center>
	<!-- <marquee direction="up"> -->
    <%= link_to (image_tag "Reliance.PNG", :title => "secrh")%> 
	</marquee>
    </center>
	</td>

    

 

  

   <td width = "200" height="100">
	<center>
	 <%= link_to "nilgiris " , list_path%> 
	 </center></br>
	<center>
	<!-- <marquee direction="up"> -->
   <%= link_to (image_tag "nilgiris.PNG", :title => "view")%> 
   </marquee>
    </center>
	</td>

  </tr>
</table>
										
									
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
							<center>
								<table width="401" height="273" border="1">
  <tr>
    <td>
	Bigbazzar
 </td>
    <td>Reliance;</td>
    <td>nilgiris;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
</center>
							</td>
						</tr>
					</table>
	 
					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>

app/views/stores/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
			<div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										<!--
										<marquee behavior="alternate"> 
											<%= link_to (image_tag "baners.PNG", :title => "baner")%>
										</marquee>
										

										 <marquee direction="right"> 
<%= link_to (image_tag "11.PNG", :title => "secrh")%>
<%= link_to (image_tag "12.PNG", :title => "secrh")%>
<%= link_to (image_tag "13.PNG", :title => "secrh")%>
<%= link_to (image_tag "14.PNG", :title => "secrh")%>
</marquee> 
-->

										
									
											
									
											
											</div>

										
									
									<h1>New store</h1>

									<%= render 'form' %>

							<!--		<%= link_to 'Back', stores_path %> -->

									
									
									
									
									
									
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
								<table width="800" border="0">
									<tr>
							
									</tr> 
									
								</table>
							</td>
						</tr>
					</table>

					&nbsp
					&nbsp
					&nbsp
					&nbsp
					&nbsp


					<center> <%= link_to "LOGOUT " , vendorsignout_path ,  method: "delete" , class: "btn btn-large btn-inverse" %> </center>
	 
					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>

app/views/stores/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
			<div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										<p id="notice"><%= notice %></p>

<p>
  <b>Store name:</b>
  <%= @store.store_name %>
</p>

<p>
  <b>Store url:</b>
  <%= @store.store_url %>
</p>

<p>
  <b>Area:</b>
  <%= @store.area %>
</p>

<p>
  <b>Location:</b>
  <%= @store.location %>
</p>

<p>
  <b>Latitude</b>
  <%= @store.latitude %>
</p>

<p>
  <b>longitude</b>
  <%= @store.longitude %>
</p>

</br>

<h3>Nearby Locations</h3>
<ul>
<%for store in @store.nearbys(10)%>
<li><%= link_to store.location, store %> (<%= store.distance %> miles)</li>


<% end %>
</ul>
</br>


<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@store.latitude}%2C#{@store.longitude}" %>

</br>
<h4> To get Directions click on google map image
</h4>
<%= link_to (image_tag "Google-Maps-icon.png", :title => "Go For Maps"), "https://maps.google.co.in/maps?hl=en&tab=wl", :target=>"_blank"   %>

	  


</br>
</br>
</br>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>


										
									
											
									
											
											</div>

										
									

							<!--		<%= link_to 'Back', stores_path %> -->

									
									
									
									
									
									
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
								<table width="800" border="0">
									<tr>
							
									</tr> 
									
								</table>
							</td>
						</tr>
					</table>



		</br>			
	 
					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>