config/routes.rb
Freekart::Application.routes.draw do

  
 

 
  get "main/coupon"
  

  resources :stores

  resources :products

    resources :vendors
	resources :vendorsessions, only: [:new, :create, :destroy]
 
  resources :contacts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

   
		match '/vendorsignup',  to: 'vendors#new'
		
		match '/vendorsignin',  to: 'vendorsessions#new'
		match '/vendorsignout', to: 'vendorsessions#destroy', via: :delete
		
   

   match '/new', to: 'contacts#new'
   match '/productnew', to: 'products#new' 
   match '/productindex', to: 'products#index' 
    match '/storenew', to: 'stores#new' 
	match '/storeindex', to: 'stores#index' 
	match '/show',  to: 'vendors#show'

	
	
         
  

  match '/signup',  to: 'users#new'

  match '/signin',   to: 'sessions#new'

  match '/signout',  to: 'sessions#destroy', via: :delete
 
	

  match '/home', to: 'shop#home'
   match '/about', to: 'shop#about'
   match '/disclaimer', to: 'shop#disclaimer'
    

   match '/categories', to: 'categories#category'
		match '/bags', to: 'categories#bags'
		match '/travelbags', to: 'categories#travelbags'
		match '/laptopbags', to: 'categories#laptopbags'

		match '/bagsaddpage1', to: 'categories#bagsaddpage1'
		match '/bagsaddpage2', to: 'categories#bagsaddpage2'
		match '/bagsaddpage3', to: 'categories#bagsaddpage3'

		match '/travelbagsaddpage1', to: 'categories#travelbagsaddpage1'
		match '/travelbagsaddpage2', to: 'categories#travelbagsaddpage2'
		match '/travelbagsaddpage3', to: 'categories#travelbagsaddpage3'

		match '/laptopbagsaddpage1', to: 'categories#laptopbagsaddpage1'
		match '/laptopbagsaddpage2', to: 'categories#laptopbagsaddpage2'
		match '/laptopbagsaddpage3', to: 'categories#laptopbagsaddpage3'

		match '/books', to: 'categories#books'
		match '/booksaddpage1', to: 'categories#booksaddpage1'
		match '/booksaddpage2', to: 'categories#booksaddpage2'
		match '/booksaddpage3', to: 'categories#booksaddpage3'

		match '/authors', to: 'categories#authors'	
		match '/authorsaddpage1', to: 'categories#authorsaddpage1'
		match '/authorsaddpage2', to: 'categories#authorsaddpage2'
		match '/authorsaddpage3', to: 'categories#authorsaddpage3'

		match '/english', to: 'categories#english'
		match '/englishaddpage1', to: 'categories#englishaddpage1'
		match '/englishaddpage2', to: 'categories#englishaddpage2'
		match '/englishaddpage3', to: 'categories#englishaddpage3'

		match '/jersey', to: 'categories#jersey'
		match '/jerseyaddpage1', to: 'categories#jerseyaddpage1'
		match '/jerseyaddpage2', to: 'categories#jerseyaddpage2'
		match '/jerseyaddpage3', to: 'categories#jerseyaddpage3'

		match '/menjersey', to: 'categories#menjersey'
		match '/menjerseyaddpage1', to: 'categories#menjerseyaddpage1'
		match '/menjerseyaddpage2', to: 'categories#menjerseyaddpage2'
		match '/menjerseyaddpage3', to: 'categories#menjerseyaddpage3'

		match '/womenjersey', to: 'categories#womenjersey'
		match '/womenjerseyaddpage1', to: 'categories#womenjerseyaddpage1'
		match '/womenjerseyaddpage2', to: 'categories#womenjerseyaddpage2'
		match '/womenjerseyaddpage3', to: 'categories#womenjerseyaddpage3'

		match '/kids', to: 'categories#kids'
		match '/kidsaddpage1', to: 'categories#kidsaddpage1'
		match '/kidsaddpage2', to: 'categories#kidsaddpage2'
		match '/kidsaddpage3', to: 'categories#kidsaddpage3'

match '/list', to: 'categories#list'

	
 

   root :to => 'shop#home'

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def home

  end

  def about
  end
 
  def disclaimer
	
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/about.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>

<style>
c:hover
{
background-color:green;
}
</style>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
			<div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										
										 
											<%= link_to (image_tag "aboutus.PNG", :title => "baner")%>
										</marquee>
											<center>
												<h2 class="style15"><c> </c></h2>
												  </center>
												  <left>
												<p>Tired of scouring the internet for deals, coupons and promotional codes in the fastest developing e-commerce industry in India? FreeIndiaCoupons.com will come to rescue.&nbsp;FreeIndiaCoupons.com  is a community driven website where shoppers themselves contribute the coupons for other shoppers to save money. We at FreeIndiaCoupons.com  validate every coupon submitted by the users and make sure the coupons are working.</p>
        <p>In this fast moving&nbsp;eCommerce&nbsp;market, never miss an offer, or let the coupon expire, For latest updated coupons   subscribe to our email newletter to get latest coupons in your email everyday.</p>
        <p>Since only price conscious consumers are likely to spend the time to claim the savings, coupons function as a form of&nbsp;price discrimination, enabling retailers to offer a lower price only to those consumers who would otherwise go elsewhere. In addition, coupons can also be targeted selectively to regional markets in which price competition is great.</p>   </left>

		<table>
 <tr>
  <td>
   Example of 			
  </td>
  <td>
   <ul class="dropv">
   <li><a href="#">drop-down links</a> in imbedded text.	
    <ul>
      <li><a href="#">Link one</a></li>
      <li><a href="#">Link two</a></li>
      <li><a href="#">Link three</a></li>		
     </ul>
    </li>
   </ul>			
  </td>	
 </tr>
</table>
											
										  
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
								<table width="100" border="1" align="left">
									<tr>
									
									</tr> 
									
								</table>
							</td>
						</tr>
					</table>
	 
					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>



app/views/shop/disclaimer.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
	<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
		<tr>
			<td valign="top">
			<td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
			<div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

				<table width="950" height="289" border="0" >
					<tr>
						<td width="150" valign="top">
							
		 
						</td>
						<td width="800" height="250">
		
						<center>
							<table width=85%  BGCOLOR="#000000"">
								<tr>
									<td>
										<td width="900" height="50"> 
										
										
											<center>
												 
	  <%= link_to (image_tag "dis.PNG", :title => "secrh")%>
	 
      <div class="style18">
	   <br/>
	    <br/>
        <p><b>
		Please read the following Terms and Conditions which are applicable to your use of FreeIndiaCoupons.com.
		</b></p>
		1. FreeIndiaCoupons.com has no involvement in the actual transaction between buyer and seller. The information contained in this web site is intended, solely to provide information for the personal use of the reader, who accepts full responsibility for its use.
<p>&nbsp;</p>
		2. FreeIndiaCoupons.com does not represent or endorse the accuracy or reliability of any information, including content or advertisements (collectively, the "materials") contained on, distributed through, or linked, downloaded or accessed from any of the services contained on this web site, or the quality of any products, information or other materials displayed, or obtained by you as a result of an advertisement or any other information or offer in or in connection with the service.
<p>&nbsp;</p>
		3. FreeIndiaCoupons.com reserves the right to cancel any listing at any time, and reserves the right to prohibit or restrict access to the Services to anyone at any time, with or without cause. Electronic mail or other forms of input to the site provided by visitors may be used by FreeIndiaCoupons.comfor any purpose without compensation to the visitor. FreeIndiaCoupons.com does not take any responsibility of the information you send to any of the listed members or as to how they use the provided information.
<p>&nbsp;</p>
		4. The information contained on this site carries no expressed or implied warranties as to accuracy, timeliness, or appropriateness for a particular purpose.FreeIndiaCoupons.com shall have no responsibility for content errors, omissions, and disclaim all liability for damages associated with user reliance on information provided at the site or any other sites which link to this site.
		 <p></p>
											
										  
									</td>
								</tr>
							</table>
						</center>
					</td>
  

					<table>	  
						<tr>
							<td>
								<table width="100" border="1" align="left">
									<tr>
									
									</tr> 
									
								</table>
							</td>
						</tr>
					</table>
	 
					<center>
					<div class="copyright">
					Copyright &copy; 
					<a href="http://www.onevega.com" class="white">Onevega</a> 
					2013. All rights reserved.
					</div>
					</center>

			</tr>
 
	</table>



app/views/shop/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">  <meta name="description" content="">
 <meta name="author" content="">

   
 <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
   


<style>
c:hover
{
background-color:orange;
}


divv
{
width:100px;
height:100px;
background:white;
position:relative;
animation-name:mymove;
animation-duration:2s;

/* Safari and Chrome */
-webkit-animation-name:mymove;
-webkit-animation-duration:0s;
}

@keyframes mymove
{
from {left:0px;}
to {left:200px;}
}

@-webkit-keyframes mymove /* Safari and Chrome */
{
from {left:0px;}
to {left:200px;}
}


.style1 {color: #FF0000}

$('.carousel').carousel({
  interval: 100
})


</style>
</head>

<body>
<table id="maintable" width="999"  height="363" border="0"  bgcolor="#6F0000" align="center">
  <tr>
    <td>
	
<div class="container">
<header class="header">
<div class="row">
	<h1 class="span6"><a href="index.html" title="bootstrap free business website template">
	<%= link_to (image_tag "logo.PNG", :title => "secrh")%> </a></h1>
	
	
	


	<div class="span6"><div class="pull-right"><br/> <a class="pull-right" href="mailto: info@bootstrappage.com"><small> E: www.onevega.com</small></a><strong><small> <br/> <c>Call (24/7) :  1234567894 </c></small></strong></div></div>
</div>

</header>

  <!-- Navbar
    ================================================== -->
  <!-- ======================================================================================================================== -->

 
<div id="myCarousel" class="carousel slide homCar">
		<div class="carousel-inner" style="border-top:0px solid #222; border-bottom:0px solid #222; border-radius:14px;">
		  <div class="item active">
			<!-- <img src="assets/bbaner.PNG" alt="#" style="min-height:250px; min-width:100%"/> -->
			<%= link_to (image_tag "1.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
			<span class="style1">	<h4> <marquee direction="left" onmouseover="this.stop();" onmouseout="this.start();">Worth to shop with coupons </marquee>  <h4> <span>
				 
			</div>
		  </div>

					


		  <div class="item ">
			<%= link_to (image_tag "2.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>Best deals in coupons  </h4>
				  
			</div>
		  </div>
		  <div class="item">
				<%= link_to (image_tag "3.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

			<div class="item">
				<%= link_to (image_tag "4.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

		  <div class="item">
				<%= link_to (image_tag "5.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

		  <div class="item">
				<%= link_to (image_tag "6.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

		  <div class="item">
				<%= link_to (image_tag "7.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

		  <div class="item">
				<%= link_to (image_tag "8.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>We work for you </h4>
				  
			</div>
		  </div>

		  <div class="item">
				<%= link_to (image_tag "9.PNG", :title => "secrh")%> 
			<div class="carousel-caption">
				  <h4>Limited offers  </h4>
				  
			</div>
		  </div>




		</div>
	<a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>


<div class="row" style="text-align:center" >
<div class="span2">
<div class="well well-small" >
<h4> 
   Coupons 
</h4>
<a href="details.html"><small> view details </small></a>
</div>
</div>
</a>
	
<div class="span2">
<div class="well well-small">
<h4>Bags </h4>
 <%= link_to "view details", bags_path %> 
</div>
</div>
			
<div class="span2">
<div class="well well-small">
<h4>Womenswear </h4>
<%= link_to "view details", womenjersey_path %>
</div>
</div>
			
<div class="span2">
<div class="well well-small">
<h4>Categories</h4>
<%= link_to "view details", categories_path %>
</div>
</div>
			
			
<div class="span2">
<div class="well well-small">
<h4>Stores</h4>
<%= link_to "view details", storenew_path %>
</div>
</div>
			
			
<div class="span2">
<div class="well well-small">
<h4>Menswear </h4>
<%= link_to "view details", menjersey_path %>
</div>
</div>
</div>



    
	
	
	
	    <marquee direction="left" color="red">
		<em> <span class="style1">
		" Offers are available only from and till to particular dates, Hurry up!!!  </span>
		<strong>-Coupons</strong> 
		
		    </em>
        </marquee>

	 <hr class="soften"/>
	
 
<!-- <marquee direction="right" onmouseover="this.stop();" onmouseout="this.start();"> -->

<div class="row">
	<div class="span4">
	<div class="thumbnail">
	<h3 style="text-align:center"> New Products</h3>	
	<%= link_to (image_tag "bag2.PNG", :title => "HandBags" ) , bags_path ,   id: "logo" %>
	<div class="caption">
	<h5> Your Website represents you</h5>	
	<p> <a>
We are helping you to buy Coupons online..  </a>
	</p>
	<a class="pull-right" href="#"></a>
	<br/>
	</div>
	</div>
	</div>
	<div class="span4">
	<div class="thumbnail">
	<h3 style="text-align:center">Book Coupons</h3>	
<%= link_to (image_tag "bag4.PNG", :title => "HandBags" ) , books_path ,   id: "logo" %>

	<div class="caption">
	<h5> For any online activities</h5>	
	<p>
	
We are helping you to buy Coupons online.. 
	</p>
	<a class="pull-right" href="#"></a>
	<br/>
	</div>
	</div>
	</div>
	<div class="span4">
	<div class="thumbnail">
	<h3 style="text-align:center">Feature Coupons</h3>	
	<%= link_to (image_tag "bag3.PNG", :title => "secrh")%> 
	<div class="caption">
	<h5>Drive your business in the fast track</h5>	
	<p>
	
We are helping you to buy Coupons online.. 
	</p>
	<a class="pull-right" href="#"></a>
	<br/>
	</div>
	</div>
	</div>
</div>
</marquee> 
<hr/>
<div class="row">
	<div class="span6">
	<div class="well well-small">
		<h3> What We Do !</h3>	
		<p>
		FreeIndiaCoupons.com is a community driven website where shoppers themselves contribute the coupons for other shoppers to save money. We at FreeIndiaCoupons.com validate every coupon submitted by the users and make sure the coupons are working.
		
		<br/><br/> In this fast moving&nbsp;eCommerce&nbsp;market, never miss an offer, or let the coupon expire, For latest updated coupons   subscribe to our email newletter to get latest coupons in your email everyday.<br/>
		</p>
	</div>
	</div>
	<div class="span6">
	<div class="well well-small">
		<h3> Customers and Vendors</h3>
		<h5>Our aim is simple</h5>	
		<p>
		"To provide affordable Coupons and discounts for different stuff is our main goal."
		</p>
		<strong> Coupon Selling Process:</strong>	
		<p>
		It is very simple process to upload your Coupons . Create an account and upload your Coupons. 
		It will be published on the website, You can track your online activity yourself.
		
		</p>
		
	</div>
	</div>
	
	
</div>
<!-- Footer
      ==================================================
<hr class="soften"/>

 -->
<footer class="footer">
<p>
	<span class="pull-right">

	 <%= link_to (image_tag "fb3.PNG", :title => "secrh"), href=" https://www.facebook.com" , :target=>"_blank"%> 
     <%= link_to (image_tag "tw.PNG", :title => "secrh") , href="https://twitter.com", :target=>"_blank"  %>
     <%= link_to (image_tag "gplus1.png", :title => "secrh"),  href="https://plus.google.com/", :target=>"_blank"%>
	 <%= link_to (image_tag "ld.png", :title => "secrh"),  href="https://linkedin.com/", :target=>"_blank"  %>
	 
	</span>
<%= link_to "Home", home_path %>-

<%= link_to "Who we are", about_path %> - 

<%= link_to "What we do?", home_path %>-

<c><%= link_to "Support",   new_path %> </c>

</p>
<hr class="soften"/>

<p>&copy;  <a href="http://www.onevega.com" class="white">Onevega</a> 
					2014. All rights reserved.<br/><br/></p> 



 </footer>
</div><!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="bootstrap/js/jquery-1.8.3.min.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
	</style>
  
	
	
	
	</td>
  </tr>
</table>

</body>
</html>