config/routes.rb
Freekart::Application.routes.draw do

  
 

 
  get "main/coupon"
  

  resources :stores

  resources :products

    resources :vendors
	resources :vendorsessions, only: [:new, :create, :destroy]
 
  resources :contacts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

   
		match '/vendorsignup',  to: 'vendors#new'
		
		match '/vendorsignin',  to: 'vendorsessions#new'
		match '/vendorsignout', to: 'vendorsessions#destroy', via: :delete
		
   

   match '/new', to: 'contacts#new'
   match '/productnew', to: 'products#new' 
   match '/productindex', to: 'products#index' 
    match '/storenew', to: 'stores#new' 
	match '/storeindex', to: 'stores#index' 
	match '/show',  to: 'vendors#show'

	
	
         
  

  match '/signup',  to: 'users#new'

  match '/signin',   to: 'sessions#new'

  match '/signout',  to: 'sessions#destroy', via: :delete
 
	

  match '/home', to: 'shop#home'
   match '/about', to: 'shop#about'
   match '/disclaimer', to: 'shop#disclaimer'
    

   match '/categories', to: 'categories#category'
		match '/bags', to: 'categories#bags'
		match '/travelbags', to: 'categories#travelbags'
		match '/laptopbags', to: 'categories#laptopbags'

		match '/bagsaddpage1', to: 'categories#bagsaddpage1'
		match '/bagsaddpage2', to: 'categories#bagsaddpage2'
		match '/bagsaddpage3', to: 'categories#bagsaddpage3'

		match '/travelbagsaddpage1', to: 'categories#travelbagsaddpage1'
		match '/travelbagsaddpage2', to: 'categories#travelbagsaddpage2'
		match '/travelbagsaddpage3', to: 'categories#travelbagsaddpage3'

		match '/laptopbagsaddpage1', to: 'categories#laptopbagsaddpage1'
		match '/laptopbagsaddpage2', to: 'categories#laptopbagsaddpage2'
		match '/laptopbagsaddpage3', to: 'categories#laptopbagsaddpage3'

		match '/books', to: 'categories#books'
		match '/booksaddpage1', to: 'categories#booksaddpage1'
		match '/booksaddpage2', to: 'categories#booksaddpage2'
		match '/booksaddpage3', to: 'categories#booksaddpage3'

		match '/authors', to: 'categories#authors'	
		match '/authorsaddpage1', to: 'categories#authorsaddpage1'
		match '/authorsaddpage2', to: 'categories#authorsaddpage2'
		match '/authorsaddpage3', to: 'categories#authorsaddpage3'

		match '/english', to: 'categories#english'
		match '/englishaddpage1', to: 'categories#englishaddpage1'
		match '/englishaddpage2', to: 'categories#englishaddpage2'
		match '/englishaddpage3', to: 'categories#englishaddpage3'

		match '/jersey', to: 'categories#jersey'
		match '/jerseyaddpage1', to: 'categories#jerseyaddpage1'
		match '/jerseyaddpage2', to: 'categories#jerseyaddpage2'
		match '/jerseyaddpage3', to: 'categories#jerseyaddpage3'

		match '/menjersey', to: 'categories#menjersey'
		match '/menjerseyaddpage1', to: 'categories#menjerseyaddpage1'
		match '/menjerseyaddpage2', to: 'categories#menjerseyaddpage2'
		match '/menjerseyaddpage3', to: 'categories#menjerseyaddpage3'

		match '/womenjersey', to: 'categories#womenjersey'
		match '/womenjerseyaddpage1', to: 'categories#womenjerseyaddpage1'
		match '/womenjerseyaddpage2', to: 'categories#womenjerseyaddpage2'
		match '/womenjerseyaddpage3', to: 'categories#womenjerseyaddpage3'

		match '/kids', to: 'categories#kids'
		match '/kidsaddpage1', to: 'categories#kidsaddpage1'
		match '/kidsaddpage2', to: 'categories#kidsaddpage2'
		match '/kidsaddpage3', to: 'categories#kidsaddpage3'

match '/list', to: 'categories#list'

	
 

   root :to => 'shop#home'

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/authorsaddpage1.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td width="250"> <%= link_to "Books", books_path , class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td width="250"> <%= link_to "Authors", authors_path , class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
       <td width="250"> <%= link_to "English", english_path , class: "btn btn-large btn-inverse" %> </td>
      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF BAGS</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "booksbaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">HANDBAGS</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "bk1.PNG", :title => "secrh")  %>
		<div class="style20">Model: Designer handbags 006
Shipping Weight: 1.8lbs
168 Units in Stock
s</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> Art Pink Handbags known as a leading and affordable luxury brand ..
	  As one of the most popular styles of designers,Designer pink Handbags already catched lady's eyes.Maybe you 
	  already 
	  have many handbags yourself,but you can reject the designer pink handbags when you saw them,as they are so visual 
	  shock and fashion topics between women. If you want to be a fashion lady,then designer pink  Handbags can provide
	  you the best styles.Fashion styles, popular color, best brand designer Handbags is the best choice!</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>




















app/views/categories/bagsaddpage1.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "Bags", bags_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "Travelbags", travelbags_path , class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td><%= link_to "Laptopbags", laptopbags_path , class: "btn btn-large btn-inverse" %></td>
      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF BAGS</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "bbaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">HANDBAGS</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "bag4.PNG", :title => "secrh")  %>
		<div class="style20">Model: Designer handbags 006
Shipping Weight: 1.8lbs
168 Units in Stock
s</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> Art Pink Handbags known as a leading and affordable luxury brand ..
	  As one of the most popular styles of designers,Designer pink Handbags already catched lady's eyes.Maybe you 
	  already 
	  have many handbags yourself,but you can reject the designer pink handbags when you saw them,as they are so visual 
	  shock and fashion topics between women. If you want to be a fashion lady,then designer pink  Handbags can provide
	  you the best styles.Fashion styles, popular color, best brand designer Handbags is the best choice!</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>



app/views/categories/jerseyaddpage3.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
         <td><%= link_to "Jerseys", jersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "MenJerseys", menjersey_path, class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td> <%= link_to "WomenJerseys", womenjersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
	  <tr>
<td> <%= link_to "Kids", kids_path, class: "btn btn-large btn-inverse" %></td>



      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF JERSEY</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "jerseybaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">JERSEY</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "wj1.PNG", :title => "secrh")  %>
		<div class="style20">Model: Women's Long-Sleeve jersey Turtlenecks 
</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> They come in five different colors. They come in different sizes</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>










app/views/categories/kidsaddpage3.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
         <td><%= link_to "Jerseys", jersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "MenJerseys", menjersey_path, class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td> <%= link_to "WomenJerseys", womenjersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
	  <tr>
<td> <%= link_to "Kids", kids_path, class: "btn btn-large btn-inverse" %></td>



      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF JERSEY</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "jerseybaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">JERSEY</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "wj1.PNG", :title => "secrh")  %>
		<div class="style20">Model: Women's Long-Sleeve jersey Turtlenecks 
</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> They come in five different colors. They come in different sizes</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>










app/views/categories/menjerseyaddpage3.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
         <td><%= link_to "Jerseys", jersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "MenJerseys", menjersey_path, class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td> <%= link_to "WomenJerseys", womenjersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
	  <tr>
<td> <%= link_to "Kids", kids_path, class: "btn btn-large btn-inverse" %></td>



      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF JERSEY</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "jerseybaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">JERSEY</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "wj1.PNG", :title => "secrh")  %>
		<div class="style20">Model: Women's Long-Sleeve jersey Turtlenecks 
</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> They come in five different colors. They come in different sizes</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>










app/views/categories/womenjersey.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "categories", categories_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "Jerseys", jersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "MenJerseys", menjersey_path, class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td> <%= link_to "WomenJerseys", womenjersey_path, class: "btn btn-large btn-inverse" %></td>
</tr>
<tr>
<td> <%= link_to "Kids", kids_path, class: "btn btn-large btn-inverse" %></td>



      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF JERSEYS</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "jerseybaner.PNG", :title => "Bags")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">WOMEN JERESYS</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top">
	<table width="945" height="281" border="0">
      <tr>
	
        <td width="200" valign="top">
		  <marquee> 
		  <%= link_to (image_tag "wj1.PNG", :title => "HandBags" ) , jerseyaddpage1_path  ,   id: "logo" %>	</marquee>  </td>
		  <td width="200"> 
			  <marquee><%= link_to (image_tag "wj4.PNG", :title => "HandBags" ) , jerseyaddpage2_path ,   id: "logo" %> 	  </marquee></td>
        <td width="200"><marquee><%= link_to (image_tag "wj3.PNG ", :title => "HandBags" ) , jerseyaddpage3_path ,   id: "logo" %></marquee></td>
		
        
        <td width="237">&nbsp;</td>
	
      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>



































app/views/categories/womenjerseyaddpage2.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Untitled Document</title>
</head>
<body bgcolor="#9C2662">
<table id="bagtable" width="999"  height="900" border="0" bgcolor="#FFFFFF" align="center">
  <tr>
     <td valign="top">
   <td width="1053" height="110" valign="top"><%= link_to (image_tag "logo.PNG", :title => "Logo")  %>
   <div style="float:right; margin-right:auto;"><span class="style17"><span class="style18"></span></span>	</div>

  <table width="950" height="289" border="0" >
      <tr>
        <td width="150" valign="top">
		<table width="150" height="285" border="0" >
      <tr>
        <td><%= link_to "Category", categories_path , class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
         <td><%= link_to "Jerseys", jersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
      <tr>
        <td><%= link_to "MenJerseys", menjersey_path, class: "btn btn-large btn-inverse" %> </td>
      </tr>
      <tr>
        <td> <%= link_to "WomenJerseys", womenjersey_path, class: "btn btn-large btn-inverse" %></td>
      </tr>
	  <tr>
<td> <%= link_to "Kids", kids_path, class: "btn btn-large btn-inverse" %></td>



      </tr>

    </table>
		 
		</td>
        <td width="800" height="250">
		
		<center>
<table width=85%  BGCOLOR="#000000"">
<tr>
<td>
<td width="800" height="50"> <BR><center><font color="#00C5CD" face="Tahoma, Geneva, sans-serif">COOL COLLECTION OF JERSEY</font></center><BR>
<marquee behavior="alternate"> 
<%= link_to (image_tag "jerseybaner.PNG", :title => "secrh")%>
</marquee>

</td>
</tr>
</table>
</center>


</td>
  



<table>	  
	 <tr>

<h2 class="style15" onclick="_gaq.push(['_trackEvent', 'hTag', 'h2Click']);">JERSEY</h2>    


	 <table width="950" height="289" border="0">
  <tr>
    <td valign="top"><table width="945" height="281" border="0">
      <tr>
	
        <td width="150"><p><%= link_to (image_tag "wj1.PNG", :title => "secrh")  %>
		<div class="style20">Model: Women's Long-Sleeve jersey Turtlenecks 
</div>
		<td width="300" valign="top"><h2 class="style19" id="productName"><b>Designer Handbags In Pink</b></h2>
	  <h2 class="style20" id="productPrices">RS.999</h2>
	  <div class="style20" id="productDescription"> They come in five different colors. They come in different sizes</div></td>

      </tr>
    </table></td>
  </tr>

</table>
	 
	<center><div class="copyright">Copyright &copy; <a href="http://www.onevega.com" class="white">Onevega</a> 2013. All rights reserved.</div></center>

	</td>
  </tr>
 <tr>


</tr>
</table>








