config/routes.rb
Freekart::Application.routes.draw do

  
 

 
  get "main/coupon"
  

  resources :stores

  resources :products

    resources :vendors
	resources :vendorsessions, only: [:new, :create, :destroy]
 
  resources :contacts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

   
		match '/vendorsignup',  to: 'vendors#new'
		
		match '/vendorsignin',  to: 'vendorsessions#new'
		match '/vendorsignout', to: 'vendorsessions#destroy', via: :delete
		
   

   match '/new', to: 'contacts#new'
   match '/productnew', to: 'products#new' 
   match '/productindex', to: 'products#index' 
    match '/storenew', to: 'stores#new' 
	match '/storeindex', to: 'stores#index' 
	match '/show',  to: 'vendors#show'

	
	
         
  

  match '/signup',  to: 'users#new'

  match '/signin',   to: 'sessions#new'

  match '/signout',  to: 'sessions#destroy', via: :delete
 
	

  match '/home', to: 'shop#home'
   match '/about', to: 'shop#about'
   match '/disclaimer', to: 'shop#disclaimer'
    

   match '/categories', to: 'categories#category'
		match '/bags', to: 'categories#bags'
		match '/travelbags', to: 'categories#travelbags'
		match '/laptopbags', to: 'categories#laptopbags'

		match '/bagsaddpage1', to: 'categories#bagsaddpage1'
		match '/bagsaddpage2', to: 'categories#bagsaddpage2'
		match '/bagsaddpage3', to: 'categories#bagsaddpage3'

		match '/travelbagsaddpage1', to: 'categories#travelbagsaddpage1'
		match '/travelbagsaddpage2', to: 'categories#travelbagsaddpage2'
		match '/travelbagsaddpage3', to: 'categories#travelbagsaddpage3'

		match '/laptopbagsaddpage1', to: 'categories#laptopbagsaddpage1'
		match '/laptopbagsaddpage2', to: 'categories#laptopbagsaddpage2'
		match '/laptopbagsaddpage3', to: 'categories#laptopbagsaddpage3'

		match '/books', to: 'categories#books'
		match '/booksaddpage1', to: 'categories#booksaddpage1'
		match '/booksaddpage2', to: 'categories#booksaddpage2'
		match '/booksaddpage3', to: 'categories#booksaddpage3'

		match '/authors', to: 'categories#authors'	
		match '/authorsaddpage1', to: 'categories#authorsaddpage1'
		match '/authorsaddpage2', to: 'categories#authorsaddpage2'
		match '/authorsaddpage3', to: 'categories#authorsaddpage3'

		match '/english', to: 'categories#english'
		match '/englishaddpage1', to: 'categories#englishaddpage1'
		match '/englishaddpage2', to: 'categories#englishaddpage2'
		match '/englishaddpage3', to: 'categories#englishaddpage3'

		match '/jersey', to: 'categories#jersey'
		match '/jerseyaddpage1', to: 'categories#jerseyaddpage1'
		match '/jerseyaddpage2', to: 'categories#jerseyaddpage2'
		match '/jerseyaddpage3', to: 'categories#jerseyaddpage3'

		match '/menjersey', to: 'categories#menjersey'
		match '/menjerseyaddpage1', to: 'categories#menjerseyaddpage1'
		match '/menjerseyaddpage2', to: 'categories#menjerseyaddpage2'
		match '/menjerseyaddpage3', to: 'categories#menjerseyaddpage3'

		match '/womenjersey', to: 'categories#womenjersey'
		match '/womenjerseyaddpage1', to: 'categories#womenjerseyaddpage1'
		match '/womenjerseyaddpage2', to: 'categories#womenjerseyaddpage2'
		match '/womenjerseyaddpage3', to: 'categories#womenjerseyaddpage3'

		match '/kids', to: 'categories#kids'
		match '/kidsaddpage1', to: 'categories#kidsaddpage1'
		match '/kidsaddpage2', to: 'categories#kidsaddpage2'
		match '/kidsaddpage3', to: 'categories#kidsaddpage3'

match '/list', to: 'categories#list'

	
 

   root :to => 'shop#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
	 
    <%= stylesheet_link_tag    'custom', :media => "all" %>
	<%= stylesheet_link_tag    'custom1', :media => "all" %>
	<%= stylesheet_link_tag    'test', :media => "all" %>
	<%= stylesheet_link_tag    'style2', :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
  </head>

  <body>

  
  
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "coupons", root_path , id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    home_path %> </button></li>
			  
			<!--  <li><%= link_to "Categories",   '#' %></li> -->
			  <li><%= link_to "Products",   categories_path %></li>
			   <li><%= link_to "About", about_path %></li>
			   <li><%= link_to "Contactus",   new_path %></li>
			  
			  <li><%= link_to "Disclaimer",    disclaimer_path %></li>
			
				
				 <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Vendors<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Vendors", vendorsignup_path %></li>
                <li><%= link_to "Vendors Sign In", vendorsignin_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", vendorsignout_path, method: "delete" %> 
                </li>
              </ul>
            </li>





            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Customer<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Customer", signup_path %></li>
                <li><%= link_to "Customer Sign In",    signin_path %></li>
                <li class="divider"></li>
                <li>
                <!--  <%= link_to "Sign out", signout_path, method: "delete" %> -->
                </li>
              </ul>
            </li>




<!--
		
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
			-->

              
                

            </ul>
          </nav>
        </div>
      </div>
    </header>
    
	<div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    
      <%= yield %>
    </div>

  </body>
</html>